### ISSUE TITLE
Don't work 100%

### ISSUE THREAD

**Issue by nickfour** [palahsu/M.Bomb#16]
~/MBomb $ 'MBomb v2.py'
MBomb v2.py: command not found
~/MBomb $ python MBomb v2.py
python: can't open file '/data/data/com.termux/files/home/MBomb/MBomb': [Errno 2] No such file or directory
~/MBomb $ python2 MBomb.py
Traceback (most recent call last):
  File "MBomb.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 13, in <module>
ImportError: No module named tqdm
~/MBomb $ python MBomb.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/MBomb/MBomb.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 13, in <module>
ModuleNotFoundError: No module named 'tqdm'
~/MBomb $

**Comment by sortalost** [comment]
bro, just pip install it...but still won't work as we cannot turn on [less scure apps in gmail](https://myaccount.google.com/lesssecureapps).
