### ISSUE TITLE
Dealing with running errors with Python 2

### ISSUE THREAD

**Issue by BDadmehr0** [palahsu/M.Bomb#18]
Traceback (most recent call last):
  File "MBomb.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 13, in <module>
ImportError: No module named tqdm

**Comment by BDadmehr0** [comment]
I think I don't have the tqdm library in Python 2
But what you didn't say in the README.md can be implemented with Python 3

OS : Zorin linux
Python 2.7.18
