### ISSUE TITLE
You have error in your code🤦

### ISSUE THREAD

**Issue by AzizMarrakech** [palahsu/M.Bomb#7]
Hello my friend
You have error in your code please fixed before you posting .
Traceback (most recent call last):
  File "MBomb.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 50, in <module>
  File "<string>", line 1
    Xxxxxxx@xxxxx.com
            ^
SyntaxError: invalid syntax

**Comment by palahsu** [comment]
> Hello my friend
> You have error in your code please fixed before you posting .
> Traceback (most recent call last):
> File "MBomb.py", line 8, in
> eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'','exec'))
> File "", line 50, in
> File "", line 1
> [Xxxxxxx@xxxxx.com](mailto:Xxxxxxx@xxxxx.com)
> ^
> SyntaxError: invalid syntax

Use version 2!

https://github.com/palahsu/MBomb/tree/master/MBomb%20v2
