### ISSUE TITLE
Won't work 

### ISSUE THREAD

**Issue by justinruck080** [palahsu/M.Bomb#8]
$ python2 MBomb.py
Traceback (most recent call last):
  File "MBomb.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 13, in <module>
ImportError: No module named tqdm

**Comment by palahsu** [comment]
> $ python2 MBomb.py
> Traceback (most recent call last):
> File "MBomb.py", line 8, in
> eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'','exec'))
> File "", line 13, in
> ImportError: No module named tqdm

If any error Use version 2!

https://github.com/palahsu/MBomb/tree/master/MBomb%20v2

and for install tqdm command: (**pkg install tqdm**)

**Comment by justinruck080** [comment]
When I do pkg install tqdm it says Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package tqdm
